"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Y1Ds21d7zQp
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { useVapi } from "@/hooks/useVapi";
import { useState } from "react";
// import io from "socket.io-client";
// const socket = io("");

export function Assistant() {
  const { start, stop } = useVapi();
  const [isConnected, setIsConnected] = useState(false);
  const [transport, setTransport] = useState("N/A");

  // useEffect(() => {
  //   socket.on("message2", (data: any) => {
  //     console.log("Recieved from SERVER ::", data);
  //     // Execute any command
  //   });
  // }, [socket]);

  // useEffect(() => {
  //   if (socket.connected) {
  //     onConnect();
  //   }

  //   function onConnect() {
  //     setIsConnected(true);
  //     setTransport(socket.io.engine.transport.name);

  //     socket.io.engine.on("upgrade", (transport) => {
  //       setTransport(transport.name);
  //     });
  //   }

  //   function onDisconnect() {
  //     setIsConnected(false);
  //     setTransport("N/A");
  //   }

  //   socket.on("connect", onConnect);
  //   socket.on("disconnect", onDisconnect);

  //   return () => {
  //     socket.off("connect", onConnect);
  //     socket.off("disconnect", onDisconnect);
  //   };
  // }, []);

  return (
    <div className="grid grid-cols-2 gap-6 p-6">
      <div className="flex flex-col gap-4">
        <Button onClick={start}>Start Call</Button>
        <Button variant="secondary" onClick={stop}>
          End Call
        </Button>
      </div>
      <div className="flex flex-col gap-4">
        <div className="flex items-center justify-between bg-primary px-4 py-2 rounded-md text-primary-foreground font-medium">
          <span>Call Status:</span>
          <span>Live</span>
        </div>
        <div className="rounded-md border bg-background p-4 shadow-sm">
          <div className="space-y-4">
            <div className="flex items-start gap-4">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>U</AvatarFallback>
              </Avatar>
              <div className="prose text-muted-foreground">
                <p>Hello, how can I assist you today?</p>
              </div>
            </div>
            <div className="flex items-start gap-4 bg-muted p-2 rounded-md">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>A</AvatarFallback>
              </Avatar>
              <div className="prose text-muted-foreground">
                <p>
                  I&apos;m doing well, thank you for asking. How can I help you
                  today?
                </p>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>U</AvatarFallback>
              </Avatar>
              <div className="prose text-muted-foreground">
                <p>
                  I have a few questions about your product and how it can
                  benefit my business.
                </p>
              </div>
            </div>
            <div className="flex items-start gap-4 bg-muted p-2 rounded-md">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>A</AvatarFallback>
              </Avatar>
              <div className="prose text-muted-foreground">
                <p>
                  Absolutely, I&apos;d be happy to discuss our product and how
                  it can help your business. What specific questions do you
                  have?
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
